name: CI/CD Testing

on:
  push:
    branches:
      - development

jobs:
  Setup-Environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

  Setup-Database-and-its-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: prerequisites for MongoDB
      run:  sudo apt-get install gnupg

    - name: Import the MongoDB public GPG Key
      run:  curl -fsSL https://pgp.mongodb.com/server-6.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg --dearmor

    - name: Creating a list file for MongoDB
      run:  echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list

    - name: Updating the package list
      run:  sudo apt-get update

    - name: Install MongoDB Package
      run:  sudo apt-get search mongodb

    - name: Start MongoDB
      run:  sudo systemctl start mongod
